# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 911cfa06c8d53390951d94372b39067fb6173fc969669d2a97b2095f2d039d8e9a7a2f43abba62bcdce014d2684a34438a5e16a6299b14cb5cc4187d87806bf4

test:
  secret_key_base: 1ebb1d34dbe8cd558fdbe50ce563b01afd27fdb9be2675336c9de4aabfe72250031f1455f11e99032a11b050b2ca181948669b9d1da964615744005525a162e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
